services:
  reef:
    container_name: reef
    #image: ghcr.io/melosso/reef:latest
    image: reef:local
    ports:
      - "8085:8085"
    volumes:
      - reef_core:/app/.core
      - reef_logs:/app/log
      - reef_db:/app/data
      - ./exports:/app/exports
    environment:
      - REEF_ENCRYPTION_KEY=YourKeyHere
      - Reef__DatabasePath=/app/data/Reef.db

volumes:
  reef_core:
  reef_logs:
  reef_db: