services:
  reef:
    container_name: reef
    image: ghcr.io/melosso/reef:latest
    ports:
      - "8085:8085"
    volumes:
      - reef_core:/app/.core
      - reef_logs:/app/log
      - reef_db:/app/reef.db
      - ./exports:/app/exports
    environment:
      - REEF_ENCRYPTION_KEY=YourKeyHere

volumes:
  reef_core:
  reef_logs:
  reef_db: