name: reef-page
services:
  reef-website:
    container_name: reef-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:80"
    environment:
      - REPO_URL=https://github.com/melosso/reef.git
      - REPO_BRANCH=main
